server:
  port: ${SERVER_PORT:8081}

application:
  kafka:
    metrics-topic: metrics-topic
  metrics: application.ready.time,jvm.memory.max,process.uptime

spring:
  profiles:
    active: ${APP_ENV:dev}
  application:
    name: metrics-producer

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
#        enable.idempotence: true
#        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 10000
        linger.ms: 0
        request.timeout.ms: 5000

        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

  task:
    scheduling:
      pool:
        size: 3

management:
  endpoints:
    web:
      exposure:
        include: health,metrics



